/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-05-30 15:35:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class report_005fresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Employee Salary Report</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #fff0f5; /* light pink */\r\n");
      out.write("            color: #660033; /* dark pink/purple */\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #d63384; /* strong pink */\r\n");
      out.write("        }\r\n");
      out.write("        table {\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            background-color: #ffe6f0; /* very light pink */\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(204, 102, 153, 0.3); /* pinkish shadow */\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: 1px solid #ffb3d9; /* pink border */\r\n");
      out.write("        }\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #d63384; /* strong pink */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        td {\r\n");
      out.write("            color: #660033;\r\n");
      out.write("        }\r\n");
      out.write("        a {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #cc3399; /* pink link */\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        .error {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #cc0033; /* red-ish for errors */\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>Employees With Salary Greater Than Input</h2>\r\n");
      out.write("\r\n");

    String salaryStr = request.getParameter("salary");
    String dbURL = "jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=UTC";
    String dbUser = "root";
    String dbPass = ""; // Replace with your actual MySQL password

    if (salaryStr == null || salaryStr.trim().isEmpty()) {

      out.write("\r\n");
      out.write("        <p class=\"error\">Salary parameter is missing.</p>\r\n");

    } else {
        try {
            double salary = Double.parseDouble(salaryStr);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            String query = "SELECT * FROM employees WHERE bsalary > ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setDouble(1, salary);
            ResultSet rs = stmt.executeQuery();

            boolean recordsFound = false;


      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Emp No</th>\r\n");
      out.write("            <th>Name</th>\r\n");
      out.write("            <th>Date of Joining</th>\r\n");
      out.write("            <th>Gender</th>\r\n");
      out.write("            <th>Basic Salary</th>\r\n");
      out.write("        </tr>\r\n");

            while (rs.next()) {
                recordsFound = true;

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( rs.getInt("empno") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getString("empname") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getDate("doj") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getString("gender") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getDouble("bsalary") );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");

            }

            if (!recordsFound) {

      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"5\" class=\"error\">No employees found with salary greater than ");
      out.print( salary );
      out.write(".</td>\r\n");
      out.write("        </tr>\r\n");

            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (NumberFormatException e) {

      out.write("\r\n");
      out.write("        <p class=\"error\">Invalid salary value provided.</p>\r\n");

        } catch (Exception e) {

      out.write("\r\n");
      out.write("        <p class=\"error\">Error: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");

        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <a href=\"report_form.jsp\">← Back to Report Form</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
